Repository acquia/blt, pull requests merged in 2018-06, with the labels that each got.

#2802 Issue #2796: Fixes failing deploys due to config status check.
  src/Robo/Inspector/Inspector.php
Labels: acsf, blocked

#2843 PHPStorm documentation
  mkdocs.yml
  readme/phpstorm.md
Labels: in progress

#2849 Update drush to ^9.3.0.
  composer.json
Labels: in progress

#2846 ACSF Factory Hooks, Deploy tasks, and Config bugfixes
  scripts/factory-hooks/db-update/db-update.sh
  scripts/factory-hooks/post-install/post-install.php
  scripts/factory-hooks/post-sites-php/includes.php
  settings/blt.settings.php
  settings/config.settings.php
Labels: acsf, bug

#2852 Reverted changes to solr config script for DrupalVM.
  scripts/drupal-vm/configure-solr.sh
Labels: drupal vm, enhancement

#2858 Fixes #2857: Documentation lists non-existant command.
  readme/project-tasks.md
Labels: bug, documentation

#2816 Fix composer patches creating extraneous core directories.
  composer.json
  composer.required.json
Labels: blocked

#2866 Updating BLT release process to include updating blt-project.
  RELEASE.md
Labels: documentation

#2894 Restructure documentation to conform to new readthedocs standards.
  docs/CONTRIBUTING.md
  docs/INSTALL.md
  docs/README.md
  docs/acsf-setup.md
  docs/adding-to-project.md
  docs/ci.md
  docs/code-review.md
  docs/committing-dependencies.md
  docs/config-split.md
  docs/configuration-management.md
  docs/creating-new-project.md
  docs/dependency-management.md
  docs/deploy.md
  docs/dev-workflow.md
  docs/drush.md
  docs/extending-blt.md
  docs/frontend.md
  docs/git-hooks.md
  docs/index.md
  docs/js/fix_search.js
  docs/local-development.md
  docs/memcache.md
  docs/multisite.md
  docs/next-steps.md
  docs/onboarding.md
  docs/os-contribution.md
  docs/patches.md
  docs/phpstorm.md
  docs/project-tasks.md
  docs/release-process.md
  docs/repo-architecture.md
  docs/simplesamlphp-setup.md
  docs/skills.md
  docs/testing.md
  docs/tooling.md
  docs/updating-blt.md
  docs/windows-install.md
  index.md
  mkdocs.yml
  scripts/git-hooks/README.md
Labels: bug, documentation

#2895 Reverse part of #2836.
  composer.suggested.json
Labels: 8.9.x, bug

#2897 Backport restructured documentation layout to 8.9.x
  docs/CONTRIBUTING.md
  docs/INSTALL.md
  docs/README.md
  docs/acsf-setup.md
  docs/adding-to-project.md
  docs/ci.md
  docs/code-review.md
  docs/committing-dependencies.md
  docs/config-split.md
  docs/configuration-management.md
  docs/creating-new-project.md
  docs/dependency-management.md
  docs/deploy.md
  docs/dev-workflow.md
  docs/drush.md
  docs/extending-blt.md
  docs/frontend.md
  docs/git-hooks.md
  docs/index.md
  docs/js/fix_search.js
  docs/local-development.md
  docs/memcache.md
  docs/multisite.md
  docs/next-steps.md
  docs/onboarding.md
  docs/os-contribution.md
  docs/patches.md
  docs/phpstorm.md
  docs/project-tasks.md
  docs/release-process.md
  docs/repo-architecture.md
  docs/simplesamlphp-setup.md
  docs/skills.md
  docs/testing.md
  docs/tooling.md
  docs/updating-blt.md
  docs/windows-install.md
  index.md
  mkdocs.yml
  scripts/git-hooks/README.md
Labels: 8.9.x, bug, documentation

#2902 Adding FAQ.
  docs/CONTRIBUTING.md
  docs/FAQ.md
  docs/README.md
  mkdocs.yml
Labels: 9.0.x, documentation

#2865 Fixes #2864 to run a redundant config import for config splits.
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: 9.1.x, bug, config

#2896 Add Acquia Cloud support to BLT alias and command
  scripts/blt/alias
  src/Robo/Commands/Blt/AliasCommand.php
  src/Robo/Inspector/Inspector.php
Labels: enhancement

#2831 Add Drupal 'trans' tag to Twig linter.
  src/Robo/Commands/Validate/TwigCommand.php
Labels: in progress
