Repository acquia/blt, pull requests merged in 2018-07, with the labels that each got.

#2927 Updates for drush 9 files and removing irrelevant drush 8 references.
  docs/onboarding.md
  scripts/blt/deploy/deploy-exclude.txt
  src/Robo/Commands/Doctor/DrushCheck.php
  src/Robo/Hooks/ValidateHook.php
  template/.gitignore
  template/drush/drush.yml
Labels: drush

#2922 Fixed #2867: Cache clear errors on ACSF deploys.
  scripts/factory-hooks/db-update/db-update.sh
Labels: acsf

#2958 Add tips for using BLT with Lando
  docs/alternative-environment-tips/lando.md
  docs/local-development.md
  mkdocs.yml
Labels: documentation

#2974 Correct invocation of wizard command.
  src/Robo/Commands/Blt/UpdateCommand.php
Labels: 9.1.x, bug

#2961 Add support for generating ACSF site aliases
  composer.json
  src/Robo/Commands/Generate/AliasesCommand.php
Labels: 9.2.x, acsf, drush, enhancement
