Repository acquia/blt, pull requests merged in 2018-02, with the labels that each got.

#2516 Suppart Drupal 8.5.x and Symfony 3.4.x.
  .travis.yml
  composer.json
  composer.required.json
  composer.suggested.json
  src/Robo/Commands/Vm/VmCommand.php
  tests/phpunit/BltProject/DrushTest.php
Labels: 9.0.x, enhancement

#2540 Allowing Symfony 3.4 packages.
  composer.json
Labels: 8.9.x

#2542 Require drupal/core ^8.5.0-beta1.
  composer.required.json
Labels: 9.0.x

#2536 Fixes #2524: Improve output of deprecation validator on failure.
  .travis.yml
  scripts/travis/.travis.yml
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Validate/AllCommand.php
  src/Robo/Commands/Validate/DeprecatedCommand.php
  template/.gitignore
  tests/phpunit/BltProject/DeprecatedCommandTest.php
Labels: enhancement

#2547 Fix simplesamlphp config memcache fatal error
  scripts/simplesamlphp/acquia_config.php
Labels: bug

#2545 Run long PHPUnit tests separately.
  .travis.yml
  RoboFile.php
  tests/phpunit/BltProject/DeprecatedCommandTest.php
Labels: enhancement

#2551 Fixes #2549: File permission error during upgrade to 9.0.0-beta2.
  src/Update/Updates.php
Labels: bug

#2553 Fixes #2550: Rogue local.yml file following upgrade.
  src/Update/Updates.php
Labels: bug

#2541 Permitting drupal/core 8.5.x and Lightning 3.1.x.
  composer.suggested.json
  template/tests/behat/example.local.yml
Labels: 8.9.x

#2562 Overwrite phpcs.xml.dist from template.
  src/Update/Updates.php
Labels: bug

#2544 Add separate include for GitLab CI.
  settings/blt.settings.php
  settings/ci.settings.php
  settings/gitlab.settings.php
Labels: enhancement

#2570 Update patch to clear Twig caches on deploys
  composer.required.json
Labels: bug

#2578 Travis success but drupal core update failed..
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: bug

#2575 Refactoring how git hooks are installed so they are found from yml configuration.
  src/Robo/Commands/Setup/SettingsCommand.php
Labels: enhancement

#2591 Add veryVerbose() and debug() methods to drush task.
  src/Robo/Tasks/DrushTask.php
Labels: enhancement

#2581 Fixes #2580: Recent Project Update throws intimidating error.
  src/Composer/Plugin.php
Labels: bug

#2588 Fixes #2587: Use strict variable interpolation in git-hooks pre-commit.
  scripts/git-hooks/pre-commit
Labels: enhancement

#2586 Update doc references to 9.x.
  RELEASE.md
  readme/config-split.md
  readme/creating-new-project.md
  readme/local-development.md
  scripts/config-split/templates/README.md.twig
  src/Robo/Commands/Acsf/AcsfCommand.php
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Git/GitCommand.php
  src/Update/Updates.php
  template/config/envs/README.md
Labels: documentation

#2585 Connects to #2582: Disabling BLT commit message.
  src/Robo/Commands/Git/GitCommand.php
Labels: bug
