Repository acquia/blt, pull requests merged in 2018-05, with the labels that each got.

#2786 Removing acsf-tools.
  src/Robo/Commands/Acsf/AcsfCommand.php
Labels: bug, in progress

#2787 Adding support for factory hooks.
  src/Robo/Commands/Artifact/FactoryHooksCommand.php
  tests/phpunit/BltProject/AcsfHooksTest.php
Labels: in progress

#2783 Remove bootstrap line from behat config.
  src/Robo/Inspector/Inspector.php
  template/tests/behat/example.local.yml
Labels: enhancement

#2735 Updating BLT README template to include more basic info.
  readme/dev-workflow.md
  template/README.md
Labels: documentation, in progress

#2788 Update INSTALL.md
  INSTALL.md
Labels: documentation

#2790 Fixes #2789: Require minimum Composer API version.
  composer.json
Labels: bug, in progress

#2798 Remove pipes from deploy sanitize find command
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 9.0.x, enhancement

#2810 Cleaning up onboarding doc
  readme/onboarding.md
Labels: documentation

#2841 Fixed Solr in DrupalVM.
  scripts/drupal-vm/configure-solr.sh
Labels: in progress
