Repository acquia/blt, pull requests merged in 2018-12, with the labels that each got.

#3231 Multisite bugfixes
  scripts/factory-hooks/post-install/post-install.php
  scripts/factory-hooks/post-settings-php/memcache.php
  scripts/factory-hooks/post-sites-php/includes.php
  settings/blt.settings.php
  settings/config.settings.php
  src/Robo/Commands/Generate/MultisiteCommand.php
  tests/phpunit/BltProject/MultiSiteTest.php
Labels: 10.0.x, 9.2.x, acsf

#3266 Pipelines pr-closed event doesn't fire.
  scripts/pipelines/acquia-pipelines.yml
Labels: 10.0.x, bug

#3273 Clarify INSTALL.md for Linux users
  docs/INSTALL.md
Labels: 10.0.x, documentation

#3288 Update db-update.sh
  scripts/factory-hooks/db-update/db-update.sh
Labels: 10.0.x, enhancement

#3289 Backport ACSF improvements from 9.2.x
  .travis.yml
  PATCHES.txt
  composer.json
  composer.required.json
  composer.suggested.json
  config/build.yml
  docs/FAQ.md
  docs/INSTALL.md
  docs/code-review.md
  docs/creating-new-project.md
  docs/deploy.md
  docs/extending-blt.md
  docs/local-development.md
  docs/memcache.md
  phpcs.xml.dist
  scripts/blt/drush/cache.php
  scripts/factory-hooks/db-update/db-update.sh
  scripts/factory-hooks/post-install/post-install.php
  scripts/factory-hooks/post-settings-php/memcache.php
  scripts/factory-hooks/post-sites-php/includes.php
  settings/blt.settings.php
  settings/cache.settings.php
  settings/config.settings.php
  src/Robo/Blt.php
  src/Robo/Commands/Generate/MultisiteCommand.php
  src/Robo/Commands/Git/GitCommand.php
  src/Robo/Commands/Saml/SimpleSamlPhpCommand.php
  src/Robo/Commands/Setup/BuildCommand.php
  src/Robo/Commands/Setup/ConfigCommand.php
  src/Robo/Commands/Tests/PhpUnitCommand.php
  src/Update/Updates.php
  tests/phpunit/Blt/PhpCsTest.php
  tests/phpunit/BltProject/MultiSiteTest.php
Labels: 9.0.x, bug, enhancement

#3293 Update db-update.sh
  scripts/factory-hooks/db-update/db-update.sh
Labels: 9.1.x, enhancement

#3298 Fix acsf global variable typos.
  scripts/factory-hooks/post-install/post-install.php
  settings/config.settings.php
  settings/default.local.settings.php
Labels: 9.1.x, bug

#3297 Fix ACSF global variable typos
  scripts/factory-hooks/post-install/post-install.php
  settings/config.settings.php
  settings/default.local.settings.php
Labels: 9.2.x, bug

#3287 Speed up composer operations
  composer.json
Labels: 10.0.x, enhancement

#3268 Docksal documentation
  docs/acsf-setup.md
  docs/alternative-environment-tips/docksal.md
  docs/alternative-environment-tips/lando.md
  docs/local-development.md
Labels: 10.0.x, documentation

#3269 Allow drush ansi disable execution time
  src/Robo/Tasks/DrushTask.php
Labels: 9.2.x, bug

#3202 Adding BLT commands for db/files cloud hooks.
  scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
  scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh
  src/Robo/Commands/Artifact/AcHooksCommand.php
Labels: 10.0.x, enhancement

#3305 Ignore platform requirements when running composer install on blt deploy
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 9.2.x, enhancement

#3309 Update db-update.sh
  scripts/factory-hooks/db-update/db-update.sh
Labels: 9.2.x

#3312 Use optimized classloader to resolve notices
  src/Robo/Commands/Setup/BuildCommand.php
  src/Update/Updates.php
  subtree-splits/blt-project/composer.json
Labels: 10.0.x

#3300 Updates ignore-existing to include .editorconfig.
  scripts/blt/ignore-existing.txt
Labels: 10.0.x, enhancement

#3314 Fix discrepancy in behavior btw create project with tag vs branch.
  src/Robo/Commands/Blt/UpdateCommand.php
Labels: 10.0.x, bug

#3190 Add assertions to remove PHPUnit notices.
  tests/phpunit/Blt/ConfigImportTest.php
  tests/phpunit/Blt/DoctorTest.php
  tests/phpunit/Blt/LightningTest.php
  tests/phpunit/Blt/PhpCsTest.php
  tests/phpunit/Blt/SetupCommandTest.php
  tests/phpunit/Blt/TestBehatCommandTest.php
  tests/phpunit/Blt/TestPhpUnitCommandTest.php
  tests/phpunit/src/BltProjectTestBase.php
Labels: 10.0.x, enhancement
