Repository acquia/blt, pull requests merged in 2018-10, with the labels that each got.

#3135 Fix the link of Memcache documentation page.
  docs/memcache.md
Labels: 9.2.x, documentation

#3120 Fixes issue #2744: Remove wikimedia/composer-merge-plugin from BLT.
  .gitignore
  RELEASE.md
  RoboFile.php
  blted8/README.md
  blted8/composer.json
  composer.json
  composer.required.json
  composer.suggested.json
  docs/creating-new-project.md
  docs/dependency-management.md
  docs/onboarding.md
  phpunit.xml.dist
  scripts/probo/.probo.yml
  src/Composer/Plugin.php
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Doctor/ComposerCheck.php
  src/Robo/Commands/Setup/SettingsCommand.php
  src/Update/Updater.php
  src/Update/Updates.php
  subtree-splits/blt-project/LICENSE.txt
  subtree-splits/blt-project/README.md
  subtree-splits/blt-project/composer.json
  subtree-splits/blt-require-dev/.gitignore
  subtree-splits/blt-require-dev/LICENSE.txt
  subtree-splits/blt-require-dev/composer.json
  template/composer.json
  template/docroot/autoload.php
  tests/phpunit/fixtures/sandbox/.gitkeep
  tests/phpunit/fixtures/sandbox/composer.json
  tests/phpunit/src/BltProjectTestBase.php
  tests/phpunit/src/SandboxManager.php
Labels: enhancement

#3117 Port PHPUnit fixes to 9.x
  composer.json
  config/build.yml
  scripts/phpunit/bootstrap.php
  src/Robo/Commands/Tests/PhpUnitCommand.php
  template/tests/phpunit/phpunit.xml
  tests/phpunit/bootstrap.php
Labels: bug

#3136 updating blt docs to cover ACSF memcache use.
  docs/memcache.md
Labels: 9.2.x, documentation

#3127 Fix INSTALL.md installation directions for Drush Launcher.
  docs/INSTALL.md
Labels: documentation

#3119 Fixes #3118: Update theme path to more standardized D8 defaults.
  config/build.yml
  docs/frontend.md
Labels: bug, documentation
