Repository acquia/blt, pull requests merged in 2018-09, with the labels that each got.

#3071 Allow PHPUnit to bootstrap from core.
  src/Robo/Commands/Tests/PhpUnitCommand.php
Labels: enhancement

#3076 Finished updating memcache config for alpha7.
  composer.suggested.json
  settings/memcache.settings.php
Labels: 9.2.x, bug

#3079 Backport #3076 to the 9.x branch
  composer.suggested.json
  settings/memcache.settings.php
Labels: 9.1.x, bug

#2946 Fixes #2945 by removing cloud hook exception for ACSF.
  scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
  src/Robo/Commands/Artifact/AcHooksCommand.php
Labels: 9.1.x, acsf, bug

#3094 Forward port #3093: Remove memcache.yml and references to it.
  settings/memcache.settings.php
  settings/memcache.yml
Labels: 9.2.x, bug

#3072 Cherry-pick in lost/abandoned commits from 9.x
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CONTRIBUTING.md
  docs/deploy.md
  docs/local-development.md
  src/Robo/Commands/Deploy/DeployCommand.php
  template/blt/blt.yml
Labels: 9.2.x, bug
