Repository acquia/blt, pull requests merged in 2018-11, with the labels that each got.

#3132 Update to Drupal Coder 8.3.x.
  composer.json
  src/Robo/Commands/Validate/PhpcsCommand.php
  src/Robo/Commands/Validate/phpcs-validate-files-bootstrap.php
  tests/phpunit/Blt/PhpCsTest.php
Labels: enhancement

#3221 Fixes #3063 by updating faq and install docs to improve install profi…
  docs/FAQ.md
  docs/creating-new-project.md
Labels: 10.0.x, documentation

#3064 Fixes #3063 by updating faq and install docs re: install profiles.
  docs/FAQ.md
  docs/creating-new-project.md
Labels: documentation

#3226 Fixes #3223 to update git docs.
  scripts/git-hooks/README.md
Labels: 10.0.x, documentation

#3186 Fixes #3185 to bring install and local docs inline.
  docs/INSTALL.md
  docs/local-development.md
Labels: 10.0.x, 9.2.x, documentation

#3230 Fixes #3122 to remove misleading jmeter example.
  docs/testing.md
Labels: 10.0.x, documentation

#3153 Clean up PHPUnit directories and namespaces.
  tests/phpunit/Blt/AcCloudHooksTest.php
  tests/phpunit/Blt/AcsfHooksTest.php
  tests/phpunit/Blt/BltConfigTest.php
  tests/phpunit/Blt/CiPipelinesTest.php
  tests/phpunit/Blt/CiTravisTest.php
  tests/phpunit/Blt/ConfigImportTest.php
  tests/phpunit/Blt/CustomCommandTest.php
  tests/phpunit/Blt/DeployTest.php
  tests/phpunit/Blt/DeprecatedCommandTest.php
  tests/phpunit/Blt/DoctorTest.php
  tests/phpunit/Blt/DrupalSettingsTest.php
  tests/phpunit/Blt/DrupalVmTest.php
  tests/phpunit/Blt/DrushTest.php
  tests/phpunit/Blt/FrontendTest.php
  tests/phpunit/Blt/LightningTest.php
  tests/phpunit/Blt/MultiSiteTest.php
  tests/phpunit/Blt/SetupCommandTest.php
  tests/phpunit/Blt/SetupGitHooksTest.php
  tests/phpunit/Blt/SetupToggleModulesTest.php
  tests/phpunit/Blt/SimpleSamlPhpTest.php
  tests/phpunit/Blt/TestBehatCommandTest.php
  tests/phpunit/Blt/TestPhpUnitCommandTest.php
  tests/phpunit/Blt/ValidateCommandTest.php
  tests/phpunit/Blt/WizardTest.php
Labels: enhancement

#3262 Fixes #3243 dry-run option for deploy.
  docs/deploy.md
Labels: 10.0.x, documentation

#3263 Fixes #3243 to clean up dry-run in deploy command.
  docs/deploy.md
Labels: 9.2.x, documentation

#3227 Fixes #3206 to include sensiolabs/security-checker and new composer s…
  composer.json
  docs/testing.md
  src/Robo/Commands/Tests/AllCommand.php
  src/Robo/Commands/Tests/SecurityUpdatesCommand.php
Labels: 10.0.x, enhancement

#3264 Adds FAQ for drush 8/9 permission denied issue.
  docs/FAQ.md
Labels: 10.0.x, documentation

#3240 Simplifying onboarding doc
  docs/onboarding.md
Labels: 10.0.x, documentation

#3198 [10.0.x] Add setup instructions for PHPStorm + PHPUnit (#1787)
  docs/phpstorm.md
Labels: 10.0.x, documentation

#3234 Update onboarding.md
  docs/onboarding.md
Labels: 10.0.x, documentation

#3235 Added instruction to install BLT and ddev.
  docs/alternative-environment-tips/ddev.md
Labels: 10.0.x, documentation

#3250 Added ddev documentation
  docs/local-development.md
Labels: 10.0.x, documentation
