Repository acquia/blt, pull requests merged in 2018-04, with the labels that each got.

#2699 Fixes #2698: corrects security update advisory text.
  src/Robo/Commands/Tests/SecurityUpdatesCommand.php
Labels: bug

#2680 Prevent unintended config export.
  src/Robo/Commands/Setup/ConfigCommand.php
  src/Robo/Inspector/Inspector.php
Labels: bug

#2701 Fixes #2696 to include config in composer munge.
  src/Robo/Common/ComposerMunge.php
Labels: enhancement

#2685 ACSF Cloud Hooks / Factory Hooks Enhancements
  scripts/cloud-hooks/functions.sh
  scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
  settings/acsf/db-update/db-update.sh
  settings/acsf/post-install/post-install.php
  settings/acsf/post-settings-php/includes.php
  settings/acsf/post-theme-deploy/clear-twig-cache.sh
Labels: enhancement

#2712 adding the apache vhost for the Drupal VM Dashboard
  scripts/drupal-vm/config.yml
Labels: enhancement

#2706 Fixes #2705: moving features override functionality and re-enabling.
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: enhancement

#2675 Fixes #2658 by moving sanitize command out of hook and into blt command.
  scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
  src/Robo/Commands/Artifact/AcHooksCommand.php
  tests/phpunit/BltProject/AcCloudHookTest.php
Labels: enhancement

#2714 Fixes #2713: Lock XDebug into an older version for compatibility with PHP 5.6.
  scripts/drupal-vm/config.yml
Labels: enhancement

#2730 Fixes #2676: Replace BLT 9 acsf command with appropriate BLT 8 command.
  settings/acsf/db-update/db-update.sh
Labels: bug, in progress

#2716 Allow config_splits to be enabled when config files are not exported.
  settings/config.settings.php
Labels: enhancement

#2702 Fixes #2697: Remove disabled git hooks.
  src/Robo/Commands/Setup/SettingsCommand.php
  tests/phpunit/BltProject/SetupGitHooksTest.php
Labels: enhancement

#2733 Fixes #1038: PHP Notice: Undefined index: gardens_site_settings.
  settings/blt.settings.php
  settings/filesystem.settings.php
Labels: bug

#2737 Fixes #2707 by resyncing the ci.blt.yml with the template file.
  src/Update/Updates.php
Labels: bug, in progress

#2745 Fixes #2742 to include a composer munge as part of the 9.1 update.
  src/Update/Updates.php
Labels: bug, in progress

#2749 Fixes #2747 to define target_env for BLT 8.x
  settings/acsf/post-install/post-install.php
Labels: bug, in progress

#2751 Fixes #2728 to properly document Drush 9 alias generation.
  readme/next-steps.md
Labels: documentation, in progress

#2748 Fixes #2747 to define target_env for BLT 9.x.
  settings/acsf/post-install/post-install.php
Labels: bug, in progress

#2752 Fixes #2718: Can't git commit image files.
  template/phpcs.xml.dist
Labels: bug, in progress

#2754 Fix broken links to CONTRIBUTING.md
  README.md
  index.md
Labels: documentation, in progress

#2763 Fixes #2762 to include missing use statement.
  src/Update/Updates.php
Labels: bug, in progress

#2772 Require ACSF ^2.47.0.
  src/Robo/Commands/Acsf/AcsfCommand.php
Labels: enhancement, in progress

#2774 Fix a little typo in documentation
  readme/updating-blt.md
Labels: documentation, in progress

#2773 Exclude .github folder from artifact.
  scripts/blt/deploy/deploy-exclude.txt
Labels: enhancement

#2770 Fixes #2760: Leverage source and target dump options for sync.
  src/Robo/Commands/Sync/SyncCommand.php
Labels: bug, in progress

#2777 Fixes #2759: Alias should search for vendor in cwd.
  scripts/blt/alias
Labels: enhancement, in progress
