Repository acquia/blt, pull requests merged in 2018-03, with the labels that each got.

#2592 Use HEAD of main Lightning branch
  composer.required.json
  composer.suggested.json
Labels: enhancement

#2595 Require drupal/features ^3.7.0.
  composer.suggested.json
Labels: enhancement

#2590 Fixes #2566: Allow site to be installed from existing config.
  src/Robo/Commands/Setup/ConfigCommand.php
  tests/phpunit/BltProject/SetupCommandTest.php
Labels: enhancement

#2596 Execute internal:drupal:install in VM.
  src/Robo/Commands/Setup/DrupalCommand.php
Labels: bug

#2597 Removing Drupal VM command proxy.
  RoboFile.php
  src/Robo/BltTasks.php
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Doctor/DoctorCommand.php
  src/Robo/Commands/Frontend/FrontendCommand.php
  src/Robo/Commands/Setup/BuildCommand.php
  src/Robo/Commands/Setup/ConfigCommand.php
  src/Robo/Commands/Setup/SettingsCommand.php
  src/Robo/Commands/Setup/ToggleModulesCommand.php
  src/Robo/Commands/Sync/SyncCommand.php
  src/Robo/Commands/Tests/AllCommand.php
  src/Robo/Commands/Tests/BehatCommand.php
  src/Robo/Commands/Vm/VmCommand.php
  src/Robo/Hooks/DrushHook.php
  src/Robo/Hooks/ExecuteInDrupalVmHook.php
  src/Robo/Inspector/Inspector.php
  tests/phpunit/BltProject/DrupalVmTest.php
Labels: enhancement

#2601 Require PHP 7 minimum.
  composer.json
Labels: enhancement

#2604 Prevent warnings in update hook.
  settings/blt.settings.php
  src/Update/Updates.php
Labels: bug

#2606 Fixing PHP 7.2 incompatibility.
  src/Robo/Hooks/CommandEventHook.php
Labels: bug

#2607 Use --environment option rather than --define.
  scripts/pipelines/setup_app
  scripts/pipelines/tests
  scripts/pipelines/validate
  scripts/travis/run_tests
  settings/acsf/db-update/db-update.sh
  settings/acsf/post-install/post-install.php
  src/Robo/Config/ConfigInitializer.php
  src/Robo/Wizards/TestsWizard.php
Labels: enhancement

#2608 Requiring drupal/core:^8.5.0, acquia/lightning:^3.1.0.
  composer.required.json
  composer.suggested.json
Labels: enhancement

#2609 Alias dev-master to 9.x-dev.
  composer.json
Labels: enhancement

#2611 Require PHP 7.1 in all the right places.
  composer.json
  scripts/travis/.travis.yml
Labels: bug

#2612 Correctly return failure in cloud hooks.
  src/Robo/Commands/Artifact/AcHooksCommand.php
Labels: bug

#2614 Add shim for symfony console 3.4 upgrade.
  bin/blt-robo-run.php
Labels: bug

#2615 Fix bug causing update failure.
  src/Composer/Plugin.php
Labels: bug

#2617 Fixes #2616: Config Splits not correctly activated.
  settings/config.settings.php
Labels: bug

#2621 Update composer.required.json.
  composer.required.json
Labels: bug

#2619 Run drush cr instead off cc-drush in SyncCommand.
  src/Robo/Commands/Sync/DbCommand.php
Labels: enhancement

#2622 Fixes #2618: Command "drupal:sync" is not defined.
  src/Robo/Commands/Sync/SyncCommand.php
Labels: bug

#2624 #2618: Use proper subcommand name.
  src/Robo/Commands/Setup/AllCommand.php
Labels: enhancement

#2625 Adding messages to 9.0.0 update hook.
  src/Update/Updates.php
Labels: enhancement

#2630 Fixes #2629: Incorrect documentation of frontend hooks.
  readme/frontend.md
Labels: documentation

#2631 Fixes #2628: Correctly pass verbosity to Drush.
  src/Robo/Tasks/DrushTask.php
  src/Robo/Tasks/LoadTasks.php
Labels: bug

#2638 Executing all tests in tests/phpunit by default.
  config/build.yml
  tests/phpunit/BltProject/TestPhpUnitCommandTest.php
  tests/phpunit/src/BltProjectTestBase.php
Labels: enhancement

#2626 Fixes #2613: Resolve error in BLT wizard. Add tests.
  src/Robo/Commands/Setup/WizardCommand.php
  src/Robo/Config/ProjectConfiguration.php
  tests/phpunit/BltProject/WizardTest.php
  tests/phpunit/fixtures/recipe.yml
Labels: enhancement

#2642 Fixes #2641: Add workaround for Drush 9 sql:sync bug.
  src/Robo/Commands/Sync/SyncCommand.php
Labels: bug

#2643 Fixes #2639: Add blt/src dir.
  template/blt/src/.gitkeep
Labels: bug

#2650 Fixes #2649: Require DrupalVM 4.8.
  src/Robo/Commands/Vm/VmCommand.php
Labels: enhancement

#2651 Fixes #2633: Make git hook symlinks relative.
  src/Robo/Commands/Setup/SettingsCommand.php
  tests/phpunit/BltProject/SetupGitHooksTest.php
Labels: bug

#2653 Fixes #2652: Readme Getting Started links 404.
  README.md
Labels: documentation

#2655 checkUriResponse should better indicate whether /etc/hosts is correctly configured
  src/Robo/Commands/Doctor/WebUriCheck.php
Labels: enhancement

#2656 Fixes #2644: Further encourage use of vagrant ssh prior to running co…
  readme/local-development.md
  src/Robo/Commands/Sync/SyncCommand.php
Labels: documentation

#2659 Suggest typhonius/acquia_cli v1.0+
  composer.json
Labels: enhancement

#2668 Fixes #2582: Config documentation fixes.
  readme/extending-blt.md
Labels: documentation

#2674 Fixes #2662: Allow newer version of chrome-mink-driver.
  composer.required.json
Labels: enhancement

#2683 Remove over-aggressive "Icon" .gitignore rule (9.x)
  scripts/blt/deploy/.gitignore
Labels: bug

#2684 Remove over-aggressive "Icon" .gitignore rule (8.9.x)
  scripts/blt/deploy/.gitignore
Labels: bug

#2681 Fix link to 8.9.x docs in readme.
  README.md
Labels: documentation

#2693 Fixes #2688: Adding ConfigContext to behat config by default.
  template/tests/behat/example.local.yml
Labels: enhancement
