Repository acquia/blt, pull requests merged in 2019-05, with the labels that each got.

#3614 Improve multisite generate command.
  .travis.yml
  phpunit.xml.dist
  src/Robo/Commands/Generate/MultisiteCommand.php
  tests/phpunit/BltProject/MultiSiteTest.php
Labels: 10.x, Enhancement

#3621 Fixes #3615 to remove sensiolabs-de/deprecation-detector.
  composer.required.json
  src/Robo/Commands/Validate/DeprecatedCommand.php
  tests/phpunit/BltProject/DeprecatedCommandTest.php
Labels: 9.2.x, Bug, Enhancement

#3646 Fixed drush alias generation loop.
  src/Robo/Commands/Generate/AliasesCommand.php
Labels: 10.x, Bug

#3629 Preserve comments in DrupalVM config when adding multisites.
  RoboFile.php
  composer.json
  composer.lock
  src/Robo/Commands/Generate/MultisiteCommand.php
  tests/phpunit/BltProject/MultiSiteTest.php
Labels: Enhancement

#3676 Fixes #3674 to repair site splits in 10.x.
  settings/config.settings.php
Labels: 10.x, Bug

#3675 Fixes #3674 to repair site splits in 9.2.x
  settings/config.settings.php
Labels: 9.2.x, Bug
