Repository acquia/blt, pull requests merged in 2019-06, with the labels that each got.

#3713 Fixes #3684 BLT docs to add KB article
  docs/config-split.md
  docs/configuration-management.md
Labels: 10.x

#3710 Fixes #3386 to add drupal check for deprecated module / theme code.
  composer.json
  composer.lock
  config/build.yml
  src/Robo/Commands/Validate/AllCommand.php
  src/Robo/Commands/Validate/DrupalCheckCommand.php
Labels: 10.x, Enhancement

#3721 DT-485: Update hook for composer autoload change.
  src/Update/Updater.php
  src/Update/Updates.php
Labels: 10.x, Change record

#3723 Fixes #3722 to add a config-status command.
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: 10.x, Enhancement

#3724 DT-536: Fix ACSF stack detection.
  src/Robo/Common/EnvironmentDetector.php
Labels: 10.x, Bug
