Repository acquia/blt, pull requests merged in 2019-02, with the labels that each got.

#3335 Fix BLT update hook.
  src/Update/Updates.php
Labels: in progress

#3356 Fixes #3355 to update devel in 10.x.
  subtree-splits/blt-project/composer.json
Labels: 10.0.x, enhancement, in progress

#3361 Pin memcache to 2.0-alpha7 until Acquia cloud is ready.
  composer.json
Labels: 10.0.x, memcache

#3363 Fixes #3345 to run db updates even when config strategy is none.
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: 10.0.x, bug, in progress

#3365 Fixes #3353 to update docs for factory hook in 9.x.
  scripts/factory-hooks/post-settings-php/memcache.php
Labels: 9.2.x, documentation, in progress

#3364 Fixes #3353 to update docs for factory hook.
  scripts/factory-hooks/post-settings-php/memcache.php
Labels: 10.0.x, documentation, in progress

#3370 Fixes #3322 to fix docs and codesniffer issues in factory hooks.
  scripts/factory-hooks/post-install/post-install.php
  scripts/factory-hooks/post-settings-php/includes.php
  scripts/factory-hooks/post-sites-php/includes.php
  scripts/factory-hooks/pre-settings-php/includes.php
Labels: 10.0.x, acsf, bug

#3181 Account for named arguments in Twig filter and function linting.
  src/Robo/Commands/Validate/TwigCommand.php
Labels: 10.0.x, enhancement

#3368 Revert "Update db-update.sh"
  scripts/factory-hooks/db-update/db-update.sh
Labels: 9.2.x, acsf, in progress

#3367 Revert "Update db-update.sh"
  scripts/factory-hooks/db-update/db-update.sh
Labels: 10.0.x, acsf, in progress

#3376 Added steps to install nfs-utils and enable access via firewalld; without it DrupalVm gets stuck at mounting NFS
  docs/INSTALL.md
Labels: 10.0.x, documentation

#3375 Fix code style standards in settings files.
  settings/default.includes.settings.php
  settings/global.settings.default.php
Labels: in progress

#3334 9.2.x: Upgrade BLT to Xenial on Travis CI
  .travis.yml
  scripts/travis/.travis.yml
  scripts/travis/setup_environment
Labels: 9.2.x, enhancement

#3381 Fixes #3322 to disable variable sniffs on factory hooks.
  scripts/factory-hooks/post-install/post-install.php
  scripts/factory-hooks/post-settings-php/includes.php
  scripts/factory-hooks/post-settings-php/memcache.php
  scripts/factory-hooks/post-sites-php/includes.php
  scripts/factory-hooks/pre-settings-php/includes.php
Labels: 10.0.x, acsf, bug, in progress

#3382 Updates release and readme docs.
  RELEASE.md
  docs/README.md
Labels: 10.0.x, documentation, in progress

#3374 Moved pipelines-deploy from build event to post-deploy event
  scripts/pipelines/acquia-pipelines.yml
Labels: 10.0.x, enhancement

#3369 Fixes #3362 for 10.x. Explains URI failure.
  scripts/blt/drush/cache.php
Labels: 10.0.x, acsf, in progress

#3380 Fixes #3379 to regenerate settings and hooks upon BLT 10.x update.
  src/Update/Updates.php
Labels: 10.0.x, bug, in progress

#3392 Test tests:acsf:validate
  scripts/cloud-hooks/hooks/README.md
  tests/phpunit/Blt/AcsfHooksTest.php
  tests/phpunit/Blt/DeployTest.php
Labels: 10.0.x, acsf, in progress

#3387 Create 10.x branch alias.
  composer.json
Labels: in progress

#3399 Fixes #3265 to expand alias documentation.
  docs/next-steps.md
  template/drush/README.md
Labels: 10.0.x, documentation, in progress

#3404 Fixes #3345 to run db updates even when config strategy is none. (#3363)
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: 9.0.x

#3402 Backport 9.2.x
  RELEASE.md
  composer.suggested.json
  docs/FAQ.md
  docs/INSTALL.md
  docs/README.md
  docs/acsf-setup.md
  docs/alternative-environment-tips/docksal.md
  docs/alternative-environment-tips/lando.md
  docs/frontend.md
  docs/local-development.md
  docs/next-steps.md
  docs/phpstorm.md
  docs/release-process.md
  docs/testing.md
  mkdocs.yml
  scripts/blt/drush/cache.php
  scripts/blt/ignore-existing.txt
  scripts/cloud-hooks/hooks/README.md
  scripts/drupal-vm/config.yml
  scripts/git-hooks/README.md
  scripts/pipelines/acquia-pipelines.yml
  scripts/travis/.travis.yml
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Commands/Setup/ConfigCommand.php
  src/Robo/Commands/Validate/AcsfCommand.php
  src/Robo/Commands/Validate/AllCommand.php
  src/Robo/Common/Executor.php
  src/Update/Updates.php
  template/README.md
  template/blt/blt.yml
  template/drush/README.md
  tests/phpunit/BltProject/AcsfHooksTest.php
  tests/phpunit/BltProject/DeployTest.php
Labels: 9.2.x, acsf, documentation, drupal vm, in progress

#3409 Fixes #3401 to backport devel update to 9.x.
  composer.suggested.json
Labels: 9.0.x, Dependency Update

#3410 Fixes #3383 to regenerate pipelines in the 9.x branch.
  scripts/pipelines/acquia-pipelines.yml
  src/Update/Updates.php
Labels: 9.0.x

#3398 Fixes #2984 to allow admin username to be set by config.
  config/build.yml
  src/Robo/Commands/Setup/DrupalCommand.php
Labels: 10.0.x, enhancement, in progress

#3413 Regenerate Factory and Cloud Hooks for 9.2.4
  src/Update/Updates.php
Labels: 9.2.x

#3414 Back port of #3408 to fix factory hooks for 9.2.x.
  scripts/factory-hooks/post-sites-php/includes.php
Labels: 9.2.x, acsf, bug

#3408 Replace includes.php $data by (stable) global variable equivalent
  scripts/factory-hooks/post-sites-php/includes.php
Labels: 10.0.x, 9.2.x, Prioritized, acsf, bug, drush
