Repository acquia/blt, pull requests merged in 2019-03, with the labels that each got.

#3415 Warn users that BLT is supported on Windows only under WSL. Updated documentation with alternatives.
  docs/windows-install.md
  src/Composer/Plugin.php
Labels: 10.0.x, 9.2.x, documentation, windows

#3419 Fixed #3366: Exclude ACSF files from code sniffing.
  template/phpcs.xml.dist
Labels: 10.0.x, enhancement, in progress

#3423 Improvements to sanitize the deploy build artifact
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 9.2.x, enhancement, in progress

#3241 Fixes #3086: Install sites from existing config.
  config/build.yml
  src/Robo/Commands/Setup/DrupalCommand.php
Labels: 10.0.x, enhancement

#3424 Issue #3039: Updated Behat docs.
  docs/testing.md
Labels: in progress

#3146 Allows Drush ANSI output to be disabled.
  config/build.yml
  src/Robo/Tasks/DrushTask.php
Labels: enhancement

#3193 [10.0.x] Add patchutils through extra_packages in VM config (#3191)
  scripts/drupal-vm/config.yml
  src/Robo/Commands/Vm/VmCommand.php
Labels: 10.0.x, drupal vm

#3237 BLT-3256: commit-msg UX improvements.
  config/build.yml
  src/Robo/Commands/Git/GitCommand.php
Labels: 9.2.x, enhancement

#3319 Speed up composer operations.
  composer.required.json
Labels: 9.2.x

#3429 Fixes #3317: Remove extraneous sql-drop.
  src/Robo/Commands/Sync/SyncCommand.php
Labels: 10.0.x, backport, bug, in progress

#3420 Move ACSF validate command to default config.
  config/build.yml
  template/blt/blt.yml
Labels: 10.0.x, 9.2.x, backport, bug

#3432 Create branch alias for 10.x-dev to 10.0.x-dev.
  composer.json
Labels: in progress

#3433 Update composer.json
  composer.json
Labels: in progress

#3434 Replace 10.0.x references with 10.x.
  RoboFile.php
  docs/README.md
  docs/deploy.md
  subtree-splits/blt-project/README.md
  subtree-splits/blt-require-dev/composer.json
Labels: in progress

#3426 Disable ANSI when BLT runs in Cloud Hooks.
  scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
  scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
  scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
  scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
  scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh
Labels: 10.0.x, backport, bug, in progress

#3435 Update README.md
  docs/README.md
Labels: in progress

#3440 Issue cloud hooks
  scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
  scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
  scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
Labels: in progress

#3442 Fixed cloud hooks error.
  scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh
  scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
  scripts/cloud-hooks/hooks/common/post-db-copy/db-scrub.sh
  scripts/cloud-hooks/hooks/common/post-db-copy/post-db-copy.sh
  scripts/cloud-hooks/hooks/common/post-files-copy/post-files-copy.sh
Labels: in progress

#3358 Fixes #3357: Don't use relative path for memcache PSR-4 path registration
  settings/memcache.settings.php
Labels: in progress, memcache

#3443 Fixes #3325: Verbose bash logging and error reporting for factory hooks.
  scripts/factory-hooks/db-update/db-update.sh
Labels: 10.0.x, Backport needed, in progress

#3439 Fixes #3050: Memcache stampede protection doesn't exist.
  settings/memcache.settings.php
Labels: 10.0.x, Backport needed

#3451 Added update note about settings.php regeneration.
  src/Update/Updates.php
Labels: in progress

#3452 Release from 'upstream', not 'origin'.
  RELEASE.md
  RoboFile.php
Labels: 10.0.x, Backport needed, in progress

#3453 Noted MySQL requirement for local testing.
  docs/CONTRIBUTING.md
Labels: 10.0.x, documentation, in progress

#3384 Update drush to 9.6.0, and robo to 1.3.4
  composer.json
  src/Robo/Config/BltConfig.php
  src/Robo/Config/DefaultConfig.php
Labels: Dependency Update, drush

#3456 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: in progress

#3457 Backport - Replace by (stable) global variable equivalent (#3408)
  scripts/factory-hooks/post-sites-php/includes.php
Labels: in progress

#3459 Clean up .travis.yml.
  .travis.yml
Labels: in progress

#3460 Remove cruft from travis ci.
  .travis.yml
Labels: in progress

#3461 Fixed #2968: Show composer validation warnings and errors.
  src/Robo/Commands/Validate/ComposerCommand.php
Labels: in progress

#3458 Update Robo and add composer.lock
  .gitignore
  composer.json
  composer.lock
  src/Robo/Config/BltConfig.php
  src/Robo/Config/DefaultConfig.php
Labels: in progress

#3462 Add composer.lock.
  .gitignore
  composer.lock
Labels: in progress

#3447 Fixed #1793: Allow custom commands via autoloader.
  bin/blt-robo-run.php
  bin/blt-robo.php
  scripts/blt/examples/Commands/ExampleCommand.php
  scripts/blt/examples/Commands/ExampleCommands.php
  src/Robo/Blt.php
  src/Robo/Commands/Blt/ExamplesCommand.php
  subtree-splits/blt-project/composer.json
Labels: 10.0.x, enhancement, in progress

#3468 Issue 3014
  docs/updating-blt.md
  src/Robo/Commands/Blt/UpdateCommand.php
Labels: 10.0.x, Backport needed, bug

#3470 Fixes #3015: Cannot run Twig or Yaml validators multiple times.
  src/Robo/Commands/Validate/TwigCommand.php
  src/Robo/Commands/Validate/YamlCommand.php
  src/Robo/Filesets/FilesetManager.php
Labels: 10.0.x, Backport needed, bug

#3473 Fix config message.
  src/Robo/Commands/Setup/ConfigCommand.php
Labels: 10.0.x, Backport needed

#3472 Fixes #3032: Ensure source files are clean before committing on Pipelines
  scripts/pipelines/build_artifact
  scripts/pipelines/setup_env
  scripts/pipelines/tests
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 9.2.x, Backport needed, bug

#3475 Fixes #3016: Commands run in parallel don't run to completion.
  src/Robo/BltTasks.php
Labels: 9.2.x, Backport needed, Bug

#3478 Fixes #3219: Move secret settings file according to public docs.
  settings/blt.settings.php
  settings/sample-secrets.settings.php
Labels: 10.x, Breaking change

#3479 Fixes #3238: Removed gitignore files from git on deploy.
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 10.x, Backport needed, Enhancement

#3481 Start testing Drupal 8.7.
  .travis.yml
  docs/CONTRIBUTING.md
  tests/phpunit/Blt/TestDrupalTestCommandTest.php
Labels: 10.x, Backport needed

#3482 Fixes #3239: build-dependencies option doesn't behave as expected.
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 10.x, Backport needed, Bug

#3483 Fixes #3242: Change private files path to support multisite.
  settings/filesystem.settings.php
Labels: 10.x, Breaking change

#3486 Fixes #3256: Add geerlingguy/drupal-vm as default base box.
  src/Robo/Commands/Vm/VmCommand.php
Labels: 10.x, Enhancement

#3487 Fixes #3272: Do not deploy files directory.
  scripts/blt/deploy/.gitignore
Labels: 10.x, Enhancement

#3485 Fixes #3247: Support content_archive module.
  scripts/blt/deploy/.gitignore
Labels: 10.x, Backport needed, Bug

#3488 Fixes #3332: Config imports should run for core-only after setup.
  src/Robo/Commands/Setup/BuildCommand.php
Labels: 10.x, Enhancement

#3495 Fixes #3344: Support commits with apostrophes.
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 9.2.x, Backport needed, Bug

#3503 Cleaned up multisite docs and best practices.
  docs/multisite.md
  src/Robo/Commands/Generate/MultisiteCommand.php
Labels: 10.x, Backport needed

#3504 Fix multisite db permissions for new sites.
  src/Robo/Commands/Generate/MultisiteCommand.php
Labels: 10.x, Backport needed, Bug

#3505 Fixes #3445: Pass site context when regenerating Behat config.
  src/Robo/Wizards/TestsWizard.php
  src/Robo/Wizards/Wizard.php
Labels: 10.x, Backport needed, Bug

#3506 Fixes #2985: Remove -y flag.
  src/Robo/Blt.php
  src/Robo/Commands/Setup/WizardCommand.php
  src/Robo/Commands/Sync/SyncCommand.php
  src/Robo/Common/Executor.php
  src/Robo/Common/IO.php
  tests/phpunit/Blt/MultiSiteTest.php
  tests/phpunit/Blt/WizardTest.php
  tests/phpunit/src/BltProjectTestBase.php
Labels: 10.x, Breaking change
