Repository acquia/blt, pull requests merged in 2019-07, with the labels that each got.

#3768 DT-577: Ensure after_failure runs during Travis tests.
  scripts/travis/run_tests
Labels: Bug

#3769 Fixes #3761 - Set Composer PHP Platform to 7.2.
  subtree-splits/blt-project/composer.json
Labels: Enhancement

#3737 Fixes #3645: Allow EnvironmentDetector to be overridden.
  scripts/tugboat/Makefile
  scripts/tugboat/README.md
  scripts/tugboat/build.sh
  scripts/tugboat/init.sh
  scripts/tugboat/install-node.sh
  scripts/tugboat/tugboat.drushrc.aliases.php
  scripts/tugboat/update.sh
  settings/blt.settings.php
  settings/tugboat.settings.php
  src/Robo/Common/EnvironmentDetector.php
Labels: Change record, Enhancement
