Repository acquia/blt, pull requests merged in 2019-04, with the labels that each got.

#3509 Delete example.multisite.yml
  config/example.multisite.yml
Labels: Architectural review

#3521 Improve Drush runserver error message.
  src/Robo/Commands/Tests/ServerCommand.php
Labels: 9.2.x, Backport needed

#3522 Fixed profile splits.
  settings/config.settings.php
Labels: Backport needed, Bug, Change record

#3530 Issue 3529: Adding --ignore-unmatch parameter so deploy stops failing.
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 10.x, Backport needed, Bug

#3531 Print output from checkDirty command.
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: Backport needed, Enhancement

#3534 Fixed coding standards in BLT settings.
  src/Robo/Commands/Setup/SettingsCommand.php
Labels: Backport needed, Enhancement

#3549 Alter run_tests not to use --yes as argument
  scripts/travis/run_tests
Labels: Bug

#3541 Fixes #3511: Check Git user before committing, set dummy user if necessary
  config/build.yml
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Hooks/ValidateHook.php
  src/Robo/Inspector/Inspector.php
  src/Robo/Tasks/GitTask.php
  src/Robo/Tasks/LoadTasks.php
Labels: 10.x, Enhancement

#3537 Don't glob global settings by default.
  docs/next-steps.md
  docs/onboarding.md
  settings/blt.settings.php
  settings/default.global.settings.php
  settings/default.includes.settings.php
  src/Robo/Commands/Setup/SettingsCommand.php
Labels: 10.x, Change record, Enhancement

#3560 run_tests should not use the --yes argument on Pipelines
  scripts/pipelines/tests
Labels: 10.x, Bug

#3539 Upgrade DrupalVM to 5, default PHP to 7.2, clean up DrupalVM config.
  scripts/drupal-vm/config.yml
  scripts/pipelines/acquia-pipelines.yml
  scripts/travis/.travis.yml
  src/Robo/Commands/Acsf/AcsfCommand.php
  src/Robo/Commands/Vm/VmCommand.php
Labels: 10.x, Change record, Enhancement

#3567 Fixed #3562: SQL sanitization should throw non-zero exit code on failure
  src/Robo/Commands/Artifact/AcHooksCommand.php
Labels: 10.x, Bug

#3570 Use a unified environment detector.
  settings/blt.settings.php
  settings/cache.settings.php
  settings/config.settings.php
  settings/filesystem.settings.php
  settings/logging.settings.php
  settings/sample-secrets.settings.php
  src/Robo/Commands/Artifact/AcHooksCommand.php
  src/Robo/Common/EnvironmentDetector.php
Labels: 10.x, Bug, Change record

#3580 Remove support for PhantomJS.
  config/build.yml
  docs/testing.md
  docs/tooling.md
  src/Robo/Commands/Tests/BehatCommand.php
  src/Robo/Commands/Tests/DrupalTestCommand.php
  src/Robo/Commands/Tests/TestsCommandBase.php
  src/Robo/Inspector/Inspector.php
  src/Robo/Wizards/TestsWizard.php
Labels: 10.x, Change record

#3582 Removed unused site-install parameter.
  src/Robo/Commands/Setup/DrupalCommand.php
Labels: 10.x

#3585 Fixes #3558: Better document local.blt.yml
  template/blt/example.local.blt.yml
Labels: 10.x

#3588 Fixes #3558: Use --no-interaction when deploying tags on Travis.
  scripts/travis/deploy_tag
Labels: 10.x, Enhancement

#3589 Add breaking changes to release notes.
  RoboFile.php
Labels: 10.x

#3587 Fixes #3583: Infinite recursion when using global.settings.php.
  bin/blt.bat
  settings/default.global.settings.php
  src/Robo/Commands/Blt/UpdateCommand.php
Labels: 10.x, Bug

#3586 Fixes #3574: Git tag needs author info, should stop deploy.
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Tasks/GitTask.php
Labels: 10.x, Bug

#3590 Fixes #3417: Don't ignore platform reqs by default during deploys
  docs/FAQ.md
  docs/tooling.md
  docs/windows-install.md
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Tasks/GitTask.php
  subtree-splits/blt-project/composer.json
Labels: 10.x, Change record, Enhancement

#3599 Fixes #3527: Change settings file include order.
  settings/blt.settings.php
  settings/default.global.settings.php
  tests/phpunit/Blt/MultiSiteTest.php
Labels: 10.x, Change record

#3598 Fixes #3575 to update profile split docs and functions.
  docs/config-split.md
  docs/configuration-management.md
  settings/config.settings.php
  src/Robo/Commands/Acsf/AcsfCommand.php
Labels: 10.x, Change record, Enhancement

#3600 Minor cleanup before release.
  composer.json
  composer.lock
  docs/FAQ.md
  docs/acsf-setup.md
  src/Update/Updates.php
  subtree-splits/blt-project/composer.json
  template/blt/blt.yml
Labels: 10.x
