Repository acquia/blt, pull requests merged in 2019-08, with the labels that each got.

#3782 DT-584: Support custom filesets via BLT plugins
  docs/extending-blt.md
  scripts/blt/examples/Filesets/ExampleFilesets.php
  src/Robo/Commands/Blt/ExamplesCommand.php
  src/Robo/Filesets/FilesetManager.php
Labels: Bug

#3778 DT-597: Run updates after CDE DB copies.
  docs/ci.md
  scripts/pipelines/acquia-pipelines.yml
  src/Robo/Commands/Artifact/AcHooksCommand.php
  src/Robo/Commands/Ci/CiCommand.php
  src/Update/Updater.php
  src/Update/Updates.php
Labels: Enhancement

#3781 Replaced tivie/php-os-detector with drupol/phposinfo.
  composer.json
  composer.lock
  src/Robo/Commands/Blt/AliasCommand.php
  src/Robo/Commands/Tests/TestsCommandBase.php
  src/Robo/Common/EnvironmentDetector.php
  src/Robo/Filesets/FilesetManager.php
  src/Robo/Inspector/Inspector.php
Labels: Enhancement

#3809 Fixes #3796: Deploy command continues despite composer failure
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: Bug

#3803 DT-575: Fixes #3802: Improve documentation of multisite Behat config and profile overrides
  docs/multisite.md
Labels: Enhancement

#3801 DT-652: Migrate memcache settings to standalone package.
  docs/memcache.md
  scripts/factory-hooks/post-settings-php/memcache.php
  settings/cache.settings.php
  settings/memcache.settings.php
  src/Update/Updates.php
  subtree-splits/blt-project/composer.json
Labels: Change record

#3829 DT-676: Fixes #3807: Fix composer warnings for Composer 1.9.0.
  src/Composer/Plugin.php
Labels: Bug

#3831 Skip drupal:update if Drupal is not installed
  src/Robo/Commands/Deploy/DeployCommand.php
  src/Robo/Inspector/Inspector.php
Labels: Bug

#3824 Fixes #3815: SQL sanitization fails when using memcache.
  src/Robo/Commands/Sync/SyncCommand.php
Labels: Bug
