Repository acquia/blt, pull requests merged in 2019-11, with the labels that each got.

#3906 DT-851: Fix local private files path.
  settings/default.local.settings.php
  src/Robo/Commands/Sync/SyncCommand.php
Labels: 11.x, Bug, Change record

#3901 DT-950: Update node version in Pipelines.
  scripts/pipelines/acquia-pipelines.yml
  scripts/pipelines/build_artifact
  scripts/pipelines/setup_app
  scripts/pipelines/setup_env
  scripts/pipelines/tests
  scripts/pipelines/validate
Labels: 11.x, Change record, Enhancement

#3902 DT-593: Codesniffing via pre-commit hook doesn't respect filesets.
  src/Robo/Commands/Git/GitCommand.php
  src/Robo/Commands/Validate/PhpcsCommand.php
  subtree-splits/blt-project/phpcs.xml.dist
  tests/phpunit/src/SetupGitHooksTest.php
Labels: 11.x, Backport needed, Bug

#3907 DT-850: Renamed sync.files config to sync.public-files.
  config/build.yml
  docs/project-tasks.md
  src/Robo/Commands/Sync/SyncCommand.php
Labels: 11.x, Change record

#3908 DT-747: Removing dependency on webflo.
  src/Robo/Commands/Tests/DrupalTestCommand.php
  src/Update/Updates.php
  subtree-splits/blt-project/composer.json
  subtree-splits/blt-require-dev/composer.json
  tests/phpunit/src/TestDrupalTestCommandTest.php
Labels: 11.x, Change record

#3909 DT-849: Fixes #3859: Better CI environment detection for BLT config.
  scripts/pipelines/build_artifact
  scripts/pipelines/setup_app
  scripts/pipelines/tests
  scripts/pipelines/validate
  scripts/travis/run_tests
  src/Robo/Common/EnvironmentDetector.php
  src/Robo/Config/ConfigInitializer.php
Labels: Enhancement

#3905 DT-878: Support Drush 10.
  composer.json
  composer.lock
Labels: 11.x, Change record

#3913 Remove clear-twig-cache.sh which is now done by the main platform
  scripts/factory-hooks/post-theme-deploy/clear-twig-cache.sh
Labels: 11.x, Backport needed

#3912 DT-658: Anonymous telemetry
  composer.json
  composer.lock
  src/Robo/Blt.php
  src/Robo/Commands/Drupal/ConfigCommand.php
  src/Robo/Commands/Drupal/ToggleModulesCommand.php
  src/Robo/Common/EnvironmentDetector.php
  src/Robo/Common/UserConfig.php
  src/Robo/Hooks/CommandEventHook.php
Labels: 11.x, Backport needed, Enhancement

#3923 DT-657: Fixes #3785: Split up examples:init command, don't run automatically
  src/Robo/Commands/Blt/UpdateCommand.php
  src/Robo/Commands/Recipes/BehatCommand.php
  src/Robo/Commands/Recipes/BltCommand.php
  src/Robo/Commands/Recipes/PhpUnitCommand.php
  subtree-splits/blt-project/blt/src/.gitkeep
  subtree-splits/blt-project/phpcs.xml.dist
  tests/phpunit/src/CustomCommandTest.php
  tests/phpunit/src/TestBehatCommandTest.php
  tests/phpunit/src/TestPhpUnitCommandTest.php
Labels: 11.x, Enhancement

#3925 DT-596: Fixes #3052: Add Git pre-push validation.
  config/build.yml
  scripts/git-hooks/pre-push
  src/Robo/Commands/Internal/GitCommand.php
Labels: 11.x, Enhancement

#3927 DT-587: Fixes #3564: Simulate deploys on TravisCI.
  scripts/blt/deploy/.gitignore
  scripts/travis/.travis.yml
  scripts/travis/deploy_branch
  scripts/travis/deploy_tag
  scripts/travis/simulate_deploy
  src/Robo/Commands/Artifact/DeployCommand.php
  subtree-splits/blt-project/.gitignore
Labels: 11.x, Enhancement

#3931 DT-971: Fixes #3917: Deprecate run-tests.sh, support Chrome for Drupal core tests.
  config/build.yml
  src/Robo/Commands/Tests/DrupalTestCommand.php
Labels: 11.x, Enhancement
