Repository acquia/blt, pull requests merged in 2019-01, with the labels that each got.

#3313 Updating BLT's docs to remove reference to nvm and point to Cog's documentation
  docs/frontend.md
  template/README.md
Labels: 10.0.x, documentation

#3330 Docksal documentation
  docs/alternative-environment-tips/ddev.md
  docs/alternative-environment-tips/docksal.md
  mkdocs.yml
  template/README.md
Labels: 10.0.x, documentation

#3331 Fix broken link to Cloud Hooks docs.
  docs/release-process.md
Labels: 10.0.x, documentation

#3337 Force stable drush version
  composer.json
Labels: in progress

#3328 Updating Drupal VM config versions.
  scripts/drupal-vm/config.yml
Labels: 10.0.x, drupal vm

#3249 [10.0.x] Drupal testing enhancements.
  config/build.yml
  docs/testing.md
  src/Robo/Commands/Tests/AllCommand.php
  src/Robo/Commands/Tests/BehatCommand.php
  src/Robo/Commands/Tests/DrupalTestCommand.php
  src/Robo/Commands/Tests/PhpUnitCommand.php
  src/Robo/Commands/Tests/RunTestsCommand.php
  src/Robo/Commands/Tests/TestsCommandBase.php
  src/Robo/Tasks/LoadTasks.php
  src/Robo/Tasks/PhpUnitTask.php
  src/Robo/Tasks/RunTestsTask.php
  src/Update/Updates.php
  template/blt/ci.blt.yml
  template/tests/behat/example.local.yml
  tests/phpunit/Blt/TestDrupalTestCommandTest.php
  tests/phpunit/Blt/TestPhpUnitCommandTest.php
Labels: 10.0.x, enhancement

#3348 Revert "[10.0.x] Drupal testing enhancements."
  config/build.yml
  docs/testing.md
  src/Robo/Commands/Tests/AllCommand.php
  src/Robo/Commands/Tests/BehatCommand.php
  src/Robo/Commands/Tests/DrupalTestCommand.php
  src/Robo/Commands/Tests/PhpUnitCommand.php
  src/Robo/Commands/Tests/RunTestsCommand.php
  src/Robo/Commands/Tests/TestsCommandBase.php
  src/Robo/Tasks/LoadTasks.php
  src/Robo/Tasks/PhpUnitTask.php
  src/Robo/Tasks/RunTestsTask.php
  src/Update/Updates.php
  template/blt/ci.blt.yml
  template/tests/behat/example.local.yml
  tests/phpunit/Blt/TestDrupalTestCommandTest.php
  tests/phpunit/Blt/TestPhpUnitCommandTest.php
Labels: in progress
