Repository acquia/blt, pull requests merged in 2019-10, with the labels that each got.

#3879 DT-879: Composer updates.
  composer.lock
  tests/phpunit/src/CiPipelinesTest.php
  tests/phpunit/src/CiTravisTest.php
  tests/phpunit/src/SetupGitHooksTest.php
  tests/phpunit/src/SetupToggleModulesTest.php
  tests/phpunit/src/TestBehatCommandTest.php
  tests/phpunit/src/TestDrupalTestCommandTest.php
Labels: Backport needed

#3877 DT-458: Removed drush alias generation.
  composer.json
  composer.lock
  src/Robo/Commands/Generate/AliasesCommand.php
Labels: Change record

#3878 DT-655: Removed selenium-server-standalone from blt-require-dev.
  composer.lock
  src/Robo/Commands/Tests/TestsCommandBase.php
  subtree-splits/blt-require-dev/composer.json
  tests/phpunit/src/TestDrupalTestCommandTest.php
Labels: 11.x, Change record

#3881 DT-880: Fixes #3869: duplicate .htaccess in composer.json with acsf:init
  src/Robo/Commands/Acsf/AcsfCommand.php
Labels: 11.x, Backport needed, Bug

#3884 Update ORCA version
  .travis.yml
  RoboFile.php
  composer.json
  composer.lock
  docs/configuration-management.md
  docs/phpstorm.md
  scripts/blt/ascii-art.txt
  src/Composer/Plugin.php
  src/Robo/Application.php
  src/Robo/Commands/Doctor/DoctorCheck.php
  src/Robo/Commands/Doctor/DrupalVmCheck.php
  src/Robo/Commands/Setup/SettingsCommand.php
  src/Robo/Commands/Vm/VmCommand.php
  src/Robo/Common/Executor.php
  src/Robo/Config/ProjectConfiguration.php
  src/Robo/Hooks/InteractHook.php
  src/Robo/Inspector/Inspector.php
  src/Robo/Tasks/DrushTask.php
  src/Update/Updates.php
  subtree-splits/blt-project/README-template.md
  tests/phpunit/src/DrupalVmTest.php
Labels: 11.x, Backport needed

#3887 Update ORCA version (#3884)
  .travis.yml
  RoboFile.php
  composer.json
  composer.lock
  docs/configuration-management.md
  docs/phpstorm.md
  scripts/blt/ascii-art.txt
  src/Composer/Plugin.php
  src/Robo/Application.php
  src/Robo/Commands/Doctor/DoctorCheck.php
  src/Robo/Commands/Doctor/DrupalVmCheck.php
  src/Robo/Commands/Generate/AliasesCommand.php
  src/Robo/Commands/Setup/SettingsCommand.php
  src/Robo/Commands/Vm/VmCommand.php
  src/Robo/Common/Executor.php
  src/Robo/Config/ProjectConfiguration.php
  src/Robo/Hooks/InteractHook.php
  src/Robo/Inspector/Inspector.php
  src/Robo/Tasks/DrushTask.php
  src/Update/Updates.php
  subtree-splits/blt-project/README-template.md
  tests/phpunit/src/DrupalVmTest.php
Labels: 10.x

#3892 TwigCommand should use configured project docroot.
  src/Robo/Commands/Validate/TwigCommand.php
Labels: 10.x, Backport needed, Bug

#3896 DT-948: Improve ACSF detection logic.
  src/Robo/Common/EnvironmentDetector.php
Labels: 11.x, Backport needed, Bug
