Repository acquia/blt, pull requests merged in 2019-12, with the labels that each got.

#3941 DT-581: Added nightwatch support.
  config/build.yml
  src/Robo/Commands/Tests/DrupalTestCommand.php
  src/Robo/Commands/Tests/NightwatchCommand.php
Labels: 11.x, Enhancement

#3937 Allow blt:init:shell-alias install confirmation to be configurable when run with --no-interaction
  config/build.yml
  src/Robo/Commands/Blt/AliasCommand.php
Labels: 10.x, Backport needed, Enhancement

#3942 DT-1035: Fixes #3929: Move Drupal Scaffold to project composer.json.
  .travis.yml
  composer.json
  composer.lock
  src/Update/Updates.php
  subtree-splits/blt-project/composer.json
Labels: 11.x, Change record, Enhancement, Subtree split

#3947 DT-980: Fixes #3922: Anonymous telemetry commands.
  src/Robo/Commands/Blt/TelemetryCommand.php
  src/Robo/Common/UserConfig.php
  src/Robo/Hooks/CommandEventHook.php
Labels: 11.x, Enhancement

#3946 DT-981: Fixes #3921: Enabled D9 deprecated code scanning by default.
  config/build.yml
Labels: 11.x, Change record, Enhancement

#3954 BLT-3953: Fix example SimpleSAMLphp code.
  scripts/simplesamlphp/acquia_config.php
Labels: Bug

#3962 DT-1082: Fixes #3957: Fix unexpected PHPCS behavior with Coder 8.3.7.
  src/Update/Updates.php
  subtree-splits/blt-project/phpcs.xml.dist
Labels: 11.x, Backport needed, Bug
