Repository acquia/blt, pull requests merged in 2020-04, with the labels that each got.

#4109 Fix logic to make sure user config directory exists.
  src/Robo/Common/UserConfig.php
Labels: 12.x, Backport needed, Bug

#4120 DT-1150: Fixes #3983: Better location for secrets.settings.php for ACSF.
  settings/blt.settings.php
  settings/config.settings.php
  settings/default.local.settings.php
  settings/filesystem.settings.php
  src/Robo/Common/EnvironmentDetector.php
Labels: 12.x, Change record, Enhancement

#4119 Fixes #4108: Dev Desktop doctor check missing env var.
  src/Robo/Doctor/DevDesktopCheck.php
Labels: 12.x, Backport needed, Bug

#4133 Fixes #4132: Removing BLT Gitlab support.
  docs/plugins.rst
  scripts/gitlab/gitlab-ci.yml
  settings/gitlab.settings.php
  src/Robo/Commands/Recipes/CiCommand.php
  src/Robo/Common/EnvironmentDetector.php
Labels: 12.x, Change record

#4138 Fixes #4136: Dynamically run all tests/validate commands in namespace.
  config/build.yml
  src/Robo/BltTasks.php
  src/Robo/Commands/Source/BuildCommand.php
  src/Robo/Commands/Source/SettingsCommand.php
  src/Robo/Commands/Tests/SecurityUpdatesCommand.php
  src/Robo/Commands/Tests/ServerCommand.php
  src/Robo/Commands/Tests/TestsAllCommand.php
  src/Robo/Commands/Tests/ValidateAllCommand.php
  src/Robo/Commands/Validate/ComposerCommand.php
  src/Robo/Commands/Validate/LintCommand.php
  src/Robo/Commands/Validate/TwigCommand.php
  src/Robo/Commands/Validate/ValidateAllCommand.php
  src/Robo/Commands/Validate/YamlCommand.php
  src/Robo/Doctor/BehatCheck.php
  src/Robo/Wizards/TestsWizard.php
  tests/phpunit/src/DoctorTest.php
Labels: 12.x
