Repository acquia/blt, pull requests merged in 2020-11, with the labels that each got.

#4276 Fixes #4275: Cannot run Yaml validator multiple times
  src/Robo/Commands/Validate/YamlCommand.php
Labels: 12.x, Bug

#4283 Travis CI: Use Bionic
  .travis.yml
  scripts/travis/.travis.yml
Labels: 12.x, Enhancement

#4284 Travis CI: Use bionic
  .travis.yml
  scripts/travis/.travis.yml
Labels: 11.x, Enhancement
