Repository acquia/blt, pull requests merged in 2020-03, with the labels that each got.

#4020 Fixes #4005: DT-1193: Remove usage of $_ENV
  scripts/simplesamlphp/acquia_config.php
  scripts/travis/setup_environment
  settings/blt.settings.php
  settings/drush-request-trace.settings.php
  settings/simplesamlphp.settings.php
  src/Robo/Commands/Drupal/ToggleModulesCommand.php
  src/Robo/Common/EnvironmentDetector.php
  src/Robo/Doctor/DevDesktopCheck.php
  tests/phpunit/Robo/EnvironmentDetectorTest.php
Labels: 11.x, Backport needed, Bug, Change record

#4043 Fixes #4005: DT-1193: Remove usage of $_ENV (#4020)
  scripts/simplesamlphp/acquia_config.php
  scripts/travis/setup_environment
  settings/blt.settings.php
  settings/drush-request-trace.settings.php
  settings/simplesamlphp.settings.php
  src/Robo/Commands/Drupal/ToggleModulesCommand.php
  src/Robo/Common/EnvironmentDetector.php
  src/Robo/Doctor/DevDesktopCheck.php
  tests/phpunit/Robo/EnvironmentDetectorTest.php
Labels: 11.x, Bug, Change record

#4044 Failed pre-push validation doesn't prevent push.
  src/Robo/Commands/Internal/GitCommand.php
Labels: 12.x, Backport needed, Bug

#4049 Fixes #4046: Remove dependency on MySQL database
  src/Robo/Inspector/Inspector.php
  src/Robo/Wizards/SetupWizard.php
Labels: Enhancement

#4060 DT-1171: Fixed #3993: Cannot run Drupal functional tests in Pipelines.
  src/Robo/Commands/Tests/DrupalTestCommand.php
Labels: 12.x, Backport needed, Bug

#4059 Removed drush-request-trace.settings.php.
  settings/blt.settings.php
  settings/drush-request-trace.settings.php
Labels: 12.x, Bug

#4076 DT-1356: Support drupal-check 1.1.1.
  composer.json
  composer.lock
Labels: 12.x, Backport needed, Enhancement

#4073 Public/Private File Sync Options Aren't Respected In "drupal:sync:all-sites"
  src/Robo/Commands/Drupal/SyncCommand.php
Labels: 12.x, Backport needed, Bug

#4074 Fix warnings due to missing env var during blt updates.
  src/Robo/Common/UserConfig.php
Labels: 12.x, Backport needed, Bug

#4075 Remove update hooks from prior to BLT 9.
  src/Robo/Common/ComposerMunge.php
  src/Update/Updates.php
Labels: 12.x
