Repository acquia/blt, pull requests merged in 2020-02, with the labels that each got.

#4001 DT-1166: Restrict drupal-check version to fix Pipelines TTY error.
  composer.json
  composer.lock
Labels: 11.x, Backport needed, Bug

#4016 Fixes #4012: Added update hook for #587 (gitignore for simulated deploys)
  src/Update/Updates.php
Labels: 11.x, Bug

#4017 Fixes #3994: Get environment detector subclass results on bootstrap.
  src/Robo/Common/EnvironmentDetector.php
Labels: Backport needed

#4023 DT-1183: Fixes #4003: Create 12.x branch of BLT Project for Drupal 9.
  .travis.yml
  docs/README.md
  subtree-splits/blt-project/composer.json
Labels: Subtree split

#4028 adding azure pipelines to plugin docs.
  docs/plugins.rst
Labels: Docs

#4029 updating readme to better represent supported drush versions.
  docs/README.md
Labels: Docs

#4026 DT-1179: Moved probo integration to plugin.
  docs/plugins.rst
  scripts/probo/.probo.yml
  scripts/probo/README.md
  scripts/probo/deploy_branch
  scripts/probo/deploy_tag
  scripts/probo/probo.drushrc.aliases.php
  scripts/probo/run_tests
  scripts/probo/setup_environment
  scripts/probo/setup_project
  settings/probo.settings.php
  src/Robo/Commands/Recipes/CiCommand.php
  src/Robo/Common/EnvironmentDetector.php
Labels: Change record

#4027 Support Chromium Browser for testing
  src/Robo/Commands/Tests/TestsCommandBase.php
Labels: Enhancement

#3997 Fixes #3998: Support PHP 7.4
  .travis.yml
  composer.json
  composer.lock
Labels: Backport needed

#4032 DT-589: Support Behat 3.4+.
  subtree-splits/blt-require-dev/composer.json
Labels: Change record, Enhancement, Subtree split
