Repository acquia/blt, pull requests merged in 2020-01, with the labels that each got.

#3975 Adds a config value for deployment docroot.
  config/build.yml
  src/Robo/Commands/Deploy/DeployCommand.php
Labels: 10.x, Enhancement

#3977 DT-1128: Fixes #3952: Contributed Drush commands deployed as subprojects
  src/Robo/Commands/Artifact/DeployCommand.php
Labels: 11.x, Backport needed, Bug

#3978 DT-1129: Avoid PHPUnit version conflict with Drupal core.
  .travis.yml
  composer.json
  composer.lock
  subtree-splits/blt-require-dev/composer.json
Labels: 11.x, Backport needed, Bug, Subtree split

#3981 DT-1141: Fixes #3980: pre-commit validation doesn't catch code standards errors.
  src/Robo/Commands/Internal/GitCommand.php
  src/Robo/Commands/Tests/PhpcsCommand.php
  tests/phpunit/src/SetupGitHooksTest.php
Labels: 11.x, Backport needed, Bug

#3982 DT-1036: Command to migrate projects to Composer Scaffold.
  src/Robo/Commands/Recipes/ScaffoldCommand.php
  src/Robo/Doctor/ComposerCheck.php
  subtree-splits/blt-project/composer.json
Labels: 11.x, Change record, Enhancement, Subtree split

#3985 Fixes #3984: updates docs to refer to PHP 7.2 and 7.3 instead of 7.1.
  docs/_markdown/INSTALL.md
  docs/install.rst
Labels: Docs

#3991 DT-1108: Fixes #3965: Stop setting tmp file path.
  settings/ci.settings.php
  settings/default.local.settings.php
Labels: Bug

#3990 Fixes #3940: DT-1053: $config_directories deprecated in Drupal 8.8.
  config/build.yml
  scripts/factory-hooks/post-settings-php/includes.php
  settings/config.settings.php
Labels: Backport needed

#3986 Added source:link command to support local package development.
  src/Robo/Commands/Blt/DevCommand.php
  src/Robo/Commands/Source/LinkPackageCommand.php
Labels: Enhancement
