Repository acquia/blt, pull requests merged in 2021-11, with the labels that each got.

#4407 Remove ORCA failing jobs
  .github/workflows/orca.yml
Labels: Chore

#4370 local.settings.php not populated correctly from example.local.blt.yml
  src/Robo/Commands/Source/SettingsCommand.php
Labels: Bug

#4385 Existing $settings['reverse_proxy_addresses'] gets clobbered
  settings/blt.settings.php
Labels: Bug

#4410 Missing pre-commit command hook
  src/Robo/Commands/Internal/GitCommand.php
  tests/phpunit/src/SetupGitHooksTest.php
Labels: Bug

#4412 Simplesamlphp wrong settings path
  settings/blt.settings.php
Labels: Bug

#4421 Remove unused code
  src/Robo/BltTasks.php
  src/Robo/Commands/Blt/DoctorCommand.php
  src/Robo/Commands/Source/LinkPackageCommand.php
  src/Robo/Doctor/DevDesktopCheck.php
  src/Robo/Inspector/Inspector.php
  tests/phpunit/src/ValidateCommandTest.php
Labels: Chore

#4423 Support Code Studio CI
  settings/codestudio.settings.php
  settings/pipelines.settings.php
  src/Robo/Common/EnvironmentDetector.php
Labels: Enhancement

#4424 Support Robo 3 and league/container 3
  composer.json
  composer.lock
  src/Robo/Blt.php
Labels: Enhancement, Minor change

#4432 Require PHP 7.4
  .github/workflows/orca.yml
  composer.json
  composer.lock
Labels: Chore, Minor change

#4433 Deprecated usage of setInput()
  src/Robo/Blt.php
  src/Robo/Tasks/DrushTask.php
  src/Robo/Tasks/LoadTasks.php
Labels: Bug
