Repository acquia/blt, pull requests merged in 2021-02, with the labels that each got.

#4334 replaces composer check for config_split module with drush check
  src/Robo/Commands/Drupal/ConfigCommand.php
Labels: Enhancement

#4340 Fix #4325: Parameters interpreted incorrectly
  src/Robo/Config/ConfigInitializer.php
Labels: Bug

#4344 Fixes #4341: package.json & package-lock.json not rsynced by default (main).
  scripts/blt/deploy/.gitignore
Labels: Enhancement

#4343 Fixes #4341: package.json and package-lock.json files not rsynced by default.
  scripts/blt/deploy/.gitignore
Labels: Enhancement

#4348 Travis CI remove Composer caching
  .travis.yml
  scripts/travis/.travis.yml
Labels: Chore

#4347 Require Composer 2
  composer.json
  composer.lock
  src/Robo/Blt.php
Labels: Chore
