Repository acquia/blt, pull requests merged in 2021-01, with the labels that each got.

#4311 Fix #4310 Skip assigning all drupal databases on local settings file
  settings/default.local.settings.php
Labels: 12.x, Enhancement

#4314 DX-3088: Fix #4300: Do not assume presence of config_split
  src/Robo/Commands/Drupal/ConfigCommand.php
  src/Robo/Inspector/Inspector.php
Labels: Enhancement

#4324 DX-3168: invokeCommand() doesn't preserve input options
  src/Robo/BltTasks.php
Labels: Bug

#4322 Update cache.settings.php for coding standard and require_once
  settings/cache.settings.php
Labels: Chore

#4328 Behat tests giving timeout error on lando.
  src/Robo/Commands/Tests/TestsCommandBase.php
Labels: Enhancement

#4329 Replace abandoned Sensiolabs security checker
  composer.json
  composer.lock
Labels: Enhancement
