Repository acquia/blt, pull requests merged in 2022-11, with the labels that each got.

#4612 Add support for drush's deploy hook.
  src/Robo/Commands/Drupal/ConfigCommand.php
Labels: Enhancement, Minor change

#4627 Fixes #4626 to remove lightning remnants.
  config/build.yml
  src/Robo/Commands/Blt/WizardCommand.php
  src/Robo/Config/ProjectConfiguration.php
Labels: Bug

#4628 Fixes #4626 removes trailing && from build.
  config/build.yml
Labels: Chore

#4629 Fixes #4625 to remove composer/xdebug-handler.
  composer.json
  composer.lock
  src/Robo/Inspector/Inspector.php
Labels: Bug

#4631 Fixes #4609 to refactor runserver command.
  src/Robo/Commands/Tests/ServerCommand.php
Labels: Bug
