Repository acquia/blt, pull requests merged in 2022-08, with the labels that each got.

#4575 Fix #4568: Use stable grasmash/yaml-expander
  composer.json
  composer.lock
Labels: Chore

#4578 Fixes #4577: refactoring global access for argv.
  src/Robo/Common/EnvironmentDetector.php
Labels: Bug

#4580 DX-5153: Add support for custom Twig tests in the Twig validator.
  config/build.yml
  src/Robo/Commands/Validate/TwigCommand.php
Labels: Enhancement

#4582 update environment detector
  composer.json
  composer.lock
  src/Robo/Common/EnvironmentDetector.php
Labels: Chore

#4586 adding key supportability matrix for BLT.
  docs/README.md
Labels: _Docs
