Repository acquia/blt, pull requests merged in 2022-02, with the labels that each got.

#4471 Fix #4464: Support Drush 11
  composer.json
  composer.lock
  src/Robo/Commands/Drupal/ConfigCommand.php
  src/Robo/Commands/Drupal/InstallCommand.php
  tests/phpunit/src/BltConfigTest.php
  tests/phpunit/src/ConfigImportTest.php
  tests/phpunit/src/SetupCommandTest.php
Labels: Minor change

#4474 Composer updates
  composer.lock
Labels: Chore

#4429 Allow admin password to be set by config if present.
  config/build.yml
  src/Robo/Commands/Drupal/InstallCommand.php
Labels: Enhancement, Minor change

#4468 Support dotaccess 2 and 3.
  composer.json
  composer.lock
Labels: Enhancement

#4460 Make private files path in default.local.settings.php multisite-aware.
  settings/default.local.settings.php
Labels: Minor change
